### ISSUE TITLE
Comment at the end of the mapping key unexpectedly starts a new line

### ISSUE THREAD

**Issue by kachick** [g-plane/pretty_yaml#2]
Using v0.2.0

Input

```yaml
jobs:
  dprint:  # comment
    runs-on: ubuntu-24.04
```

Expected

```yaml
jobs:
  dprint: # comment
    runs-on: ubuntu-24.04
```

Actual

```yaml
jobs:
  dprint:
    # comment
    runs-on: ubuntu-24.04
```
