### ISSUE TITLE
failed to handle array without element(null)

### ISSUE THREAD

**Issue by trim21** [g-plane/pretty_yaml#8]
```yaml
a:
  b:
    aliases:
      - a
      -
  c:

```

this become 

```yaml
a:
  b:
    aliases:
      - a
      - c:
```

which is not same yaml
